# Generated by Django 3.2.11 on 2023-05-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_email',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
